/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as KlienKontakRouteImport } from './routes/klien-kontak'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as ProyekLegalitasRouteImport } from './routes/proyek-legalitas'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const KlienKontakRoute = KlienKontakRouteImport.update({
  id: '/klien-kontak',
  path: '/klien-kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyekLegalitasRoute = ProyekLegalitasRouteImport.update({
  id: '/proyek-legalitas',
  path: '/proyek-legalitas',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtikelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/klien-kontak': typeof KlienKontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/proyek-legalitas': typeof ProyekLegalitasRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/klien-kontak': typeof KlienKontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/proyek-legalitas': typeof ProyekLegalitasRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/klien-kontak': typeof KlienKontakRoute
  '/layanan': typeof LayananRoute
  '/produk': typeof ProdukRoute
  '/proyek-legalitas': typeof ProyekLegalitasRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/klien-kontak'
    | '/layanan'
    | '/produk'
    | '/proyek-legalitas'
    | '/tentang-kami'
    | '/artikel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/klien-kontak'
    | '/layanan'
    | '/produk'
    | '/proyek-legalitas'
    | '/tentang-kami'
    | '/artikel/$slug'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/klien-kontak'
    | '/layanan'
    | '/produk'
    | '/proyek-legalitas'
    | '/tentang-kami'
    | '/artikel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRouteWithChildren
  KlienKontakRoute: typeof KlienKontakRoute
  LayananRoute: typeof LayananRoute
  ProdukRoute: typeof ProdukRoute
  ProyekLegalitasRoute: typeof ProyekLegalitasRoute
  TentangKamiRoute: typeof TentangKamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klien-kontak': {
      id: '/klien-kontak'
      path: '/klien-kontak'
      fullPath: '/klien-kontak'
      preLoaderRoute: typeof KlienKontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyek-legalitas': {
      id: '/proyek-legalitas'
      path: '/proyek-legalitas'
      fullPath: '/proyek-legalitas'
      preLoaderRoute: typeof ProyekLegalitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof ArtikelRoute
    }
  }
}

interface ArtikelRouteChildren {
  ArtikelSlugRoute: typeof ArtikelSlugRoute
}

const ArtikelRouteChildren: ArtikelRouteChildren = {
  ArtikelSlugRoute: ArtikelSlugRoute,
}

const ArtikelRouteWithChildren =
  ArtikelRoute._addFileChildren(ArtikelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRouteWithChildren,
  KlienKontakRoute: KlienKontakRoute,
  LayananRoute: LayananRoute,
  ProdukRoute: ProdukRoute,
  ProyekLegalitasRoute: ProyekLegalitasRoute,
  TentangKamiRoute: TentangKamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
